/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuscontatos;

import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Teixeira
 * v1 - 2019
 */
public class Frameprincipal extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Frameprincipal() {
        initComponents();
        preencherJlist();
        iniciaTitulos();
        iniciaBotoes();
        iniciaCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscrolp_vis = new javax.swing.JScrollPane();
        jPanel_vis = new javax.swing.JPanel();
        jscrollp_nomes = new javax.swing.JScrollPane();
        jList_nomes = new javax.swing.JList<>();
        jPanel_menu = new javax.swing.JPanel();
        jtf_pesquisar = new javax.swing.JTextField();
        jbt_novo = new javax.swing.JButton();
        jbt_editar = new javax.swing.JButton();
        jbt_excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MeusContatos");
        setPreferredSize(new java.awt.Dimension(549, 370));

        jscrolp_vis.setPreferredSize(new java.awt.Dimension(416, 318));

        javax.swing.GroupLayout jPanel_visLayout = new javax.swing.GroupLayout(jPanel_vis);
        jPanel_vis.setLayout(jPanel_visLayout);
        jPanel_visLayout.setHorizontalGroup(
            jPanel_visLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        jPanel_visLayout.setVerticalGroup(
            jPanel_visLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jscrolp_vis.setViewportView(jPanel_vis);

        jscrollp_nomes.setMaximumSize(new java.awt.Dimension(133, 32767));

        jList_nomes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jList_nomes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_nomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList_nomesMousePressed(evt);
            }
        });
        jscrollp_nomes.setViewportView(jList_nomes);

        jPanel_menu.setMaximumSize(new java.awt.Dimension(32767, 44));

        jtf_pesquisar.setForeground(new java.awt.Color(153, 153, 153));
        jtf_pesquisar.setText("pesquisar...");
        jtf_pesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_pesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_pesquisarFocusLost(evt);
            }
        });

        jbt_novo.setText("Novo");
        jbt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_novoActionPerformed(evt);
            }
        });

        jbt_editar.setText("Editar");
        jbt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_editarActionPerformed(evt);
            }
        });

        jbt_excluir.setText("Excluir");
        jbt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jbt_novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_excluir)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_novo)
                    .addComponent(jbt_editar)
                    .addComponent(jbt_excluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jscrollp_nomes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscrolp_vis, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jPanel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscrolp_vis, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jscrollp_nomes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_excluirActionPerformed
        int resp;
        resp = JOptionPane.showConfirmDialog(null, "Tem certeza?");
    }//GEN-LAST:event_jbt_excluirActionPerformed

    private void jtf_pesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_pesquisarFocusGained
        jtf_pesquisar.selectAll();
        jtf_pesquisar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jtf_pesquisarFocusGained

    private void jtf_pesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_pesquisarFocusLost
        if (jtf_pesquisar.getText().equalsIgnoreCase("")) {
            jtf_pesquisar.setText("pesquisar...");
            jtf_pesquisar.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jtf_pesquisarFocusLost

    private void jList_nomesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_nomesMousePressed
        //Limpa os componentes do jpanel
        jPanel_vis.removeAll();


        //Variáveis dos componentes
        JLabel[] label_info;
        label_info = new JLabel[7];
        JPanel jpanelft = new JPanel();
        JPanel jpaneltitulo = new JPanel();
        label_info[0] = new JLabel("Fulano de tal");

        //Jpanel com layout box, que permite adicionar na vertical ou na horizontal
        jpanelft.setLayout(new BoxLayout(jpanelft, BoxLayout.LINE_AXIS));
        jpaneltitulo.setLayout(new BoxLayout(jpaneltitulo, BoxLayout.PAGE_AXIS));
        //carregando a imagem em tamanho 60x60
        jlabel_foto = new JLabel(new ImageIcon(new ImageIcon(getClass()
                .getResource("media/user1.png")).getImage()
                .getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH)));

        jpaneltitulo.add(label_titulo[0]);
        label_titulo[0].setAlignmentX((float) 0.1);
        jpaneltitulo.add(label_info[0]);
        jpanelft.add(jpaneltitulo);
        jpanelft.add(Box.createHorizontalGlue());
        jpanelft.add(jlabel_foto);
        jpanelft.setAlignmentX((float) 0.05);
        jPanel_vis.add(jpanelft);
        jPanel_vis.add(Box.createRigidArea(new Dimension(0,10)));
        for (int i = 1; i < 7; i++) {
           label_info[i] = new JLabel("item n - "+i);
           label_titulo[i].setAlignmentX((float) 0.1);
           jPanel_vis.add(label_titulo[i]);
           jPanel_vis.add(label_info[i]);
           jPanel_vis.add(Box.createRigidArea(new Dimension(0,10)));
        }
         jPanel_vis.setBorder(BorderFactory.createEmptyBorder(10, 10, 0, 10));
        jscrolp_vis.validate();
    }//GEN-LAST:event_jList_nomesMousePressed

    private void jbt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_novoActionPerformed
        atualizarCompontentes(false);
    }//GEN-LAST:event_jbt_novoActionPerformed

    private void jbt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_editarActionPerformed
        atualizarCompontentes(true);
    }//GEN-LAST:event_jbt_editarActionPerformed

   private void preencherJlist(){
       String[] nomes = { "<html>Fulano<br><font size=-1>71999929292</font></html>",
                "<html>Fulanora<br><font size=-1>71999929292</font></html>",
                "<html>Sicrano<br><font size=-1>71989929292</font></html>",
                "<html>Fulanoaldo<br><font size=-1>71991929292</font></html>",
                "<html>Fulaninho<br><font size=-1>71996929292</font></html>",
                "<html>Sicraninho<br><font size=-1>71929929292</font></html>",
                "<html>Fulanera<br><font size=-1>71993929292l</font></html>"
            };
       jList_nomes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = nomes;
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
   }
   
   private void iniciaTitulos(){
        jPanel_vis.setLayout(new BoxLayout(jPanel_vis, BoxLayout.PAGE_AXIS));
        label_titulo = new JLabel[7];
        label_titulo[0] = new JLabel("<html><h3>Nome</h3></html>");
        label_titulo[1] = new JLabel("<html><h3>CPF</h3></html>");
        label_titulo[2] = new JLabel("<html><h3>Estado Civil</h3></html>");
        label_titulo[3] = new JLabel("<html><h3>Profissão</h3></html>");
        label_titulo[4] = new JLabel("<html><h3>Telefone</h3></html>");
        label_titulo[5] = new JLabel("<html><h3>E-mail</h3></html>");
        label_titulo[6] = new JLabel("<html><h3>Eendereço</h3></html>");
   }
   
   private void iniciaBotoes(){
       jbsalvar = new JButton("Salvar");
       jbcancelar = new JButton("Cancelar");
   }
   
   private void iniciaCombobox(){
       String[] estadoscivis = {"Solteiro", "Casado", "Separado", "Divorciado"};
       jc_estadocivil = new JComboBox(estadoscivis);
   }
   
   private void atualizarCompontentes(boolean com_valores){
       //Limpa os componentes do jpanel
        jPanel_vis.removeAll();

        //Variáveis dos componentes
        JTextField[] jtextf_info;
        jtextf_info = new JTextField[7];
        JPanel jpanelft = new JPanel();
        JPanel jpaneltitulo = new JPanel();
        JPanel jpanelbotoes = new JPanel();
        if(com_valores){
            jtextf_info[0] = new JTextField("nome de fulano");
        }else{
            jtextf_info[0] = new JTextField();
        }
        
        //Jpanel com layout box, que permite adicionar na vertical ou na horizontal
        jpanelft.setLayout(new BoxLayout(jpanelft, BoxLayout.LINE_AXIS));
        jpaneltitulo.setLayout(new BoxLayout(jpaneltitulo, BoxLayout.PAGE_AXIS));
        jpanelbotoes.setLayout(new BoxLayout(jpanelbotoes, BoxLayout.LINE_AXIS));
        //carregando a imagem em tamanho 60x60
        jlabel_foto = new JLabel(new ImageIcon(new ImageIcon(getClass()
                .getResource("media/user1.png")).getImage()
                .getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH)));

        jpaneltitulo.add(label_titulo[0]);
        label_titulo[0].setAlignmentX((float) 0.1);
        jpaneltitulo.add(jtextf_info[0]);
        jpanelft.add(jpaneltitulo);
        jpanelft.add(Box.createHorizontalGlue());
        jpanelft.add(jlabel_foto);
        jpanelft.setAlignmentX((float) 0.05);
        jpanelbotoes.add(Box.createHorizontalGlue());
        jpanelbotoes.add(jbsalvar);
        jpanelbotoes.add(Box.createRigidArea(new Dimension(0,10)));
        jpanelbotoes.add(jbcancelar);
        jpanelft.setAlignmentX((float) 0.05);
        jPanel_vis.add(jpanelft);
        jPanel_vis.add(Box.createRigidArea(new Dimension(0,10)));
        
        for (int i = 1; i < 7; i++) {
            if(com_valores){
                jtextf_info[i] = new JTextField("Informação "+i);
            }else{
                jtextf_info[i] = new JTextField();
            }
            label_titulo[i].setAlignmentX((float) 0.1);
            jPanel_vis.add(label_titulo[i]);
            if (i == 2) {
             jPanel_vis.add(jc_estadocivil);
            } else {
             jPanel_vis.add(jtextf_info[i]);
            }
            jPanel_vis.add(Box.createRigidArea(new Dimension(0,10)));
        }
        jPanel_vis.add(jpanelbotoes);
        jPanel_vis.setBorder(BorderFactory.createEmptyBorder(10, 10, 0, 10));
        jscrolp_vis.validate();
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frameprincipal().setVisible(true);
        });
    }

    JLabel[] label_titulo;
    JLabel jlabel_foto;
    JButton jbsalvar ;
    JButton jbcancelar;
    JComboBox jc_estadocivil;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList_nomes;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_vis;
    private javax.swing.JButton jbt_editar;
    private javax.swing.JButton jbt_excluir;
    private javax.swing.JButton jbt_novo;
    private javax.swing.JScrollPane jscrollp_nomes;
    private javax.swing.JScrollPane jscrolp_vis;
    private javax.swing.JTextField jtf_pesquisar;
    // End of variables declaration//GEN-END:variables
}
